#!/bin/bash
# Copyright (c) 2020-2025 IAR Systems AB
#
# `license-setup`
#   Configures a license volume with configuration (BX)
#
# See LICENSE for detailed license information
#

function _bx_show_help()
{
  echo "Usage: ${BASH_SOURCE[0]} iarsystems/bx<image>:<tag> <iar-license-server-ip>"
  echo "Example:"
  echo "  ${BASH_SOURCE[0]} iarsystems/bxarm:9.60.2 iar-license-server.corp.com"
  echo " "
}

function _bx-license-setup()
{
  if [ $# -ne 2 ]; then
    _bx_show_help
    return 1
  fi

  printf -- "-- setup-license: Creating a Docker volume for storing persistent license information...\n"
  docker volume create LMS2 2>&1 > /dev/null

  printf -- "-- setup-license: Running a container for setting up the license...\n"
  docker run \
    --quiet \
    --rm \
    --detach \
    --tty \
    --volume LMS2:/usr/local/etc/IARSystems \
    --name bx-license-setup \
    ${1} 2>&1 > /dev/null

  PACKAGE_DIR=$(docker exec bx-license-setup find /opt/iarsystems -type l)

  printf -- "-- setup-license: Setting up the license with IAR Light License Manager...\n"
  docker exec bx-license-setup ${PACKAGE_DIR}/common/bin/lightlicensemanager setup -s ${2} 2>&1 > /dev/null

  printf -- "-- setup-license: Finished.\n"
  docker stop bx-license-setup 2>&1 >/dev/null
}

_bx-license-setup $@
unset -f _bx-license-setup
unset -f _bx_show_help
