#!/bin/bash

#
# Copyright (c) 2020-2021 IAR Systems AB
#
# aliases-unset
#
# Unset the IAR Build Tools Docker image aliases
#
# See LICENSE for detailed license information
#

function _bx_show_help()
{
  echo "Usage: source ${BASH_SOURCE[0]}" 
  echo " "  
}

function _bx-aliases-unset()
{
  if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    echo "ERROR: the script is not being properly sourced."
    _bx_show_help
    return 1
  fi

  if [ $# -ne 0 ]; then
    _bx_show_help
    return 1
  fi
  
  local BX_INTERACTIVE_LIST=(bxarm bxarmfs bxriscv bxriscvfs bxrh850 bxrh850fs bxrx bxrxfs)
  local BX_ALIAS_LIST=($(alias | grep iarsystems | cut -f 2 -d ' ' | cut -f 1 -d= | xargs))
  printf -- "-- Unsetting aliases for IAR Build Tools Docker images.\n"
  if [ -z ${BX_ALIAS_LIST} ]; then
    printf "   .. no aliases for iarsystems/* Docker images were previously set.\n"
    return 1
  fi
  for BX_ALIAS in ${BX_ALIAS_LIST[@]}; do
    if [[ ${BX_INTERACTIVE_LIST[@]} =~ ${BX_ALIAS%-docker*} ]]; then
      printf "   .. Aliases for iarsystems/%s were unset.\n" ${BX_ALIAS%-docker*}
    fi
    unalias ${BX_ALIAS}                        2>/dev/null
  done
}

_bx-aliases-unset $@
unset -f _bx-aliases-unset
unset -f _bx_show_help
