#!/bin/bash
#
# Copyright (c) 2020-2025 IAR Systems AB
# See LICENSE for detailed license information
# 
# Bash autocompletion for `iarbuild` 
#

_iarbuild()
{
 local cur prev words cword split opts
  _init_completion -s -n : || return

  opts=$(compgen -W '$(_parse_help "$1")')

  # remove repeated options
  for ((i = 1; i < cword; i++)); do
    case ${words[i]} in
      -clean|-build|-make|-jsondb|-compdb|-ninja|-cstat_analyze|-cstat_cmds|-cstat_report|-cstat_clean|-cspybat_cmds)
        opts=${opts//-clean/}
        opts=${opts//-build/}
        opts=${opts//-make/}
        opts=${opts//-jsondb/}
        opts=${opts//-compdb/}
        opts=${opts//-ninja/}
        opts=${opts//-cstat_analyze/}
        opts=${opts//-cstat_report/}
        opts=${opts//-cstat_clean/}
        opts=${opts//-cstat_cmds/}
        opts=${opts//-cspybat_cmds/}
        ;;
      -log|-parallel|-varfile|-output|-tool|-output_type)
        opts=${opts//${words[i]}/}
    esac
  done

  case $COMP_CWORD in
    1)
      _filedir "ewp"
      return
      ;;
    2)
      opts=${opts//-log/}
      opts=${opts//-parallel/}
      opts=${opts//-varfile/}
      opts=${opts//-output/}
      opts=${opts//-tool/}
      opts=${opts//-output_type/}
      ;;
    *)
      case $prev in
        -make | -build | -clean | -compdb | -cspybat_cmds | -cstat* | -jsondb | -ninja)
        COMPREPLY=( $(compgen -W "$(grep -A1 '<configuration>' ${COMP_WORDS[1]} | grep -oP '(?<=<name>).*?(?=</name>)')" -- ${cur}) )
        return;;
      -log)
        COMPREPLY=( $(compgen -W 'all errors info warnings' -- "${cur}") )
        [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
        return;;
      -parallel)
        COMPREPLY=( $(compgen -W "{1..$(_ncpus)}" -- "${cur}") )
        [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
        return;;
      -output_type)
        COMPREPLY=( $(compgen -W 'sh bat ps' -- "${cur}") )
        [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
        return;;
      -varfile)
        _filedir "argvars"
        return;;
      esac
  esac

  $split && return

  case ${cur} in
    -*)
      COMPREPLY=( $(compgen -W "$opts" -- "${cur}") )
      [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
      return
      ;;
  esac
}
complete -o nosort -F _iarbuild iarbuild

